name: Build
on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit message"
        required: true
        default: "Update portfolio"
jobs:
  build:
    runs-on: self-hosted
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Install
        run: npm i
      - name: Build
        run: npm run build
      - name: Deploy
        run: |
          cd dist
          git init
          git remote add origin git@github.com:cgaeta/cgaeta.github.io.git
          git fetch origin
          git co origin/master -- CNAME
          git add .
          git commit -m "${{ github.event.inputs.commit }}"
          git push -f git@github.com:cgaeta/cgaeta.github.io.git master:master
