name: Build
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: |
          npm i
          npm run build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
  deploy:
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
permissions:
  pages: write
  id-token: write
