name: Build
on:
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy
    uses: cgaeta/actions/.github/workflows/build_portfolio.yml@main
    with:
      repo: astro_portfolio
      build_path: dist
    secrets:
      SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
permissions:
  contents: write
