name: Build
on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit message"
        required: true
        default: "Update portfolio"
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Deploy
        uses: cgaeta/actions/.github/workflows/build_portfolio.yml@main
        with:
          repo: astro_portfolio
          build_path: dist
