name: Build
on:
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy
    uses: cgaeta/actions/.github/workflows/build_portfolio.yml@v1
    with:
      repo: astro_portfolio
      build_path: dist
    secrets: inherit
